In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import time
from collections import defaultdict

import os
import _ParlayANNpy as pann
import numpy as np
import wrapper as wp
from scipy.sparse import csr_matrix

In [2]:
FERN_DATA_DIR = "/ssd1/anndata/bigann/"
AWARE_DATA_DIR = "/ssd1/data/bigann/"

DATA_DIR = FERN_DATA_DIR
POINTS_PATH = DATA_DIR + "data/yfcc100M/base.10M.u8bin.crop_nb_10000000"
FILTER_PATH = DATA_DIR + 'data/yfcc100M/base.metadata.10M.spmat'

In [3]:
ds = wp.FilteredDataset(POINTS_PATH, FILTER_PATH)

Detected 10000000 points with dimension 192


In [4]:
ds.distance(244, 897) # distance between two points

4033018.0

In [5]:
(ds.size(), ds.get_n_filters()) # (number of points in the dataset, number of filters in the dataset)

(10000000, 200386)

In [6]:
(ds.get_filter_size(0), ds.get_point_size(0)) # (number of points associated with the first filter, number of filters associated with the first point) 
# these are kinda useless idk why I added them

(97940, 13)

In [7]:
ds.get_filter_points(87983) # numpy array of points with label 87983

array([  58816,  113064,  188955,  370216,  434003,  434004,  469554,
        920850, 1254536, 1360330, 1774795, 2083236, 2266041, 2321204,
       2416130, 2427195, 2595615, 2595920, 2595921, 2695724, 2794821,
       2794822, 2796437, 3008463, 3008464, 3365302, 3766123, 3899782,
       3988855, 4309074, 4597811, 4650614, 5045215, 5153757, 5198273,
       5268804, 5268805, 5268806, 5300685, 5386043, 5425117, 5597575,
       5634004, 5658301, 5726002, 5789477, 5820154], dtype=int32)

In [8]:
ds.get_point_filters(244) # numpy array of filters for point 244

array([    3,    21,    23,   762,  1228,  1460,  3295,  6299, 10176,
       10177, 10178], dtype=int32)

In [9]:
ds.get_filter_intersection(2, 244) # numpy array of points that have both label 2 and 244

array([4205554, 4651584, 6189153, 6321122, 6455802, 6519911, 6733346,
       6758710, 6833602, 7076657, 7091664, 7548083, 7561881, 7807613,
       7876423, 7948812, 7985118, 8008618, 8227361, 8227362, 8464785,
       9134880, 9228882, 9449009, 9544341, 9671039], dtype=int32)

In [10]:
ds.get_point_intersection(4205554, 4651584) # numpy array of filters that both point 4205554 and 4651584 have

array([    2,    16,    29,   244,  1398,  1856,  4008, 72586],
      dtype=int32)